--
-- Table structure for table `country`
--

CREATE TABLE `country` (
  `id` int(11) NOT NULL,
  `short_name` varchar(60) NOT NULL,
  `name` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
--
-- Indexes for table `country`
--
ALTER TABLE `country`
  ADD PRIMARY KEY (`id`);


-- AUTO_INCREMENT for table `country`
--
ALTER TABLE `country`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
  
  

INSERT INTO `country` (``,`short_name`, `name`) VALUES ('AF', 'Afghanistan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AX', 'Åland Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AL', 'Albania');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DZ', 'Algeria');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AS', 'American Samoa');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AD', 'Andorra');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AO', 'Angola');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AI', 'Anguilla');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AQ', 'Antarctica');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AG', 'Antigua & Barbuda');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AR', 'Argentina');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AM', 'Armenia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AW', 'Aruba');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AU', 'Australia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AT', 'Austria');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AZ', 'Azerbaijan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BS', 'Bahamas');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BH', 'Bahrain');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BD', 'Bangladesh');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BB', 'Barbados');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BY', 'Belarus');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BE', 'Belgium');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BZ', 'Belize');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BJ', 'Benin');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BM', 'Bermuda');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BT', 'Bhutan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BO', 'Bolivia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BA', 'Bosnia & Herzegovina');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BW', 'Botswana');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BV', 'Bouvet Island');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BR', 'Brazil');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VG', 'British Virgin Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BN', 'Brunei');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BG', 'Bulgaria');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BF', 'Burkina Faso');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BI', 'Burundi');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KH', 'Cambodia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CM', 'Cameroon');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CA', 'Canada');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CV', 'Cape Verde');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KY', 'Cayman Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CF', 'Central African Republic');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TD', 'Chad');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CL', 'Chile');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CN', 'China');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CX', 'Christmas Island');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CO', 'Colombia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KM', 'Comoros');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CK', 'Cook Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CR', 'Costa Rica');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HR', 'Croatia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CU', 'Cuba');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CW', 'Curaçao');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CY', 'Cyprus');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CZ', 'Czechia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DK', 'Denmark');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DJ', 'Djibouti');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DM', 'Dominica');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DO', 'Dominican Republic');
INSERT INTO `country` (`short_name`, `name`) VALUES ('EC', 'Ecuador');
INSERT INTO `country` (`short_name`, `name`) VALUES ('EG', 'Egypt');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SV', 'El Salvador');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ER', 'Eritrea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('EE', 'Estonia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SZ', 'Eswatini');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ET', 'Ethiopia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FK', 'Falkland Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FO', 'Faroe Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FJ', 'Fiji');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FI', 'Finland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FR', 'France');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GF', 'French Guiana');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PF', 'French Polynesia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TF', 'French Southern Territories');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GA', 'Gabon');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GM', 'Gambia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GE', 'Georgia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('DE', 'Germany');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GH', 'Ghana');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GI', 'Gibraltar');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GR', 'Greece');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GL', 'Greenland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GD', 'Grenada');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GP', 'Guadeloupe');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GU', 'Guam');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GT', 'Guatemala');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GG', 'Guernsey');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GN', 'Guinea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GY', 'Guyana');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HT', 'Haiti');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HM', 'Heard & McDonald Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HN', 'Honduras');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO `country` (`short_name`, `name`) VALUES ('HU', 'Hungary');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IS', 'Iceland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IN', 'India');
INSERT INTO `country` (`short_name`, `name`) VALUES ('short_name', 'Indonesia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IR', 'Iran');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IQ', 'Iraq');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IE', 'Ireland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IM', 'Isle of Man');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IL', 'Israel');
INSERT INTO `country` (`short_name`, `name`) VALUES ('IT', 'Italy');
INSERT INTO `country` (`short_name`, `name`) VALUES ('JM', 'Jamaica');
INSERT INTO `country` (`short_name`, `name`) VALUES ('JP', 'Japan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('JE', 'Jersey');
INSERT INTO `country` (`short_name`, `name`) VALUES ('JO', 'Jordan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KZ', 'Kazakhstan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KE', 'Kenya');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KI', 'Kiribati');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KW', 'Kuwait');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LA', 'Laos');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LV', 'Latvia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LB', 'Lebanon');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LS', 'Lesotho');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LR', 'Liberia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LY', 'Libya');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LI', 'Liechtenstein');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LT', 'Lithuania');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LU', 'Luxembourg');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MO', 'Macao SAR China');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MG', 'Madagascar');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MW', 'Malawi');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MY', 'Malaysia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MV', 'Maldives');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ML', 'Mali');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MT', 'Malta');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MH', 'Marshall Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MQ', 'Martinique');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MR', 'Mauritania');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MU', 'Mauritius');
INSERT INTO `country` (`short_name`, `name`) VALUES ('YT', 'Mayotte');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MX', 'Mexico');
INSERT INTO `country` (`short_name`, `name`) VALUES ('FM', 'Micronesia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MD', 'Moldova');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MC', 'Monaco');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MN', 'Mongolia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ME', 'Montenegro');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MS', 'Montserrat');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MA', 'Morocco');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MZ', 'Mozambique');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MM', 'Myanmar (Burma)');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NA', 'Namibia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NR', 'Nauru');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NP', 'Nepal');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NL', 'Netherlands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NC', 'New Caledonia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NZ', 'New Zealand');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NI', 'Nicaragua');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NE', 'Niger');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NG', 'Nigeria');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NU', 'Niue');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NF', 'Norfolk Island');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KP', 'North Korea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MK', 'North Macedonia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('NO', 'Norway');
INSERT INTO `country` (`short_name`, `name`) VALUES ('OM', 'Oman');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PK', 'Pakistan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PW', 'Palau');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PS', 'Palestinian Territories');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PA', 'Panama');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PG', 'Papua New Guinea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PY', 'Paraguay');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PE', 'Peru');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PH', 'Philippines');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PN', 'Pitcairn Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PL', 'Poland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PT', 'Portugal');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PR', 'Puerto Rico');
INSERT INTO `country` (`short_name`, `name`) VALUES ('QA', 'Qatar');
INSERT INTO `country` (`short_name`, `name`) VALUES ('RE', 'Réunion');
INSERT INTO `country` (`short_name`, `name`) VALUES ('RO', 'Romania');
INSERT INTO `country` (`short_name`, `name`) VALUES ('RU', 'Russia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('RW', 'Rwanda');
INSERT INTO `country` (`short_name`, `name`) VALUES ('WS', 'Samoa');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SM', 'San Marino');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ST', 'São Tomé & Príncipe');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SA', 'Saudi Arabia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SN', 'Senegal');
INSERT INTO `country` (`short_name`, `name`) VALUES ('RS', 'Serbia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SC', 'Seychelles');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SL', 'Sierra Leone');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SG', 'Singapore');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SX', 'Sint Maarten');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SK', 'Slovakia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SI', 'Slovenia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SB', 'Solomon Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SO', 'Somalia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ZA', 'South Africa');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GS', 'South Georgia & South Sandwich Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KR', 'South Korea');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SS', 'South Sudan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ES', 'Spain');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LK', 'Sri Lanka');
INSERT INTO `country` (`short_name`, `name`) VALUES ('BL', 'St. Barthélemy');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SH', 'St. Helena');
INSERT INTO `country` (`short_name`, `name`) VALUES ('KN', 'St. Kitts & Nevis');
INSERT INTO `country` (`short_name`, `name`) VALUES ('LC', 'St. Lucia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('MF', 'St. Martin');
INSERT INTO `country` (`short_name`, `name`) VALUES ('PM', 'St. Pierre & Miquelon');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VC', 'St. Vincent & Grenadines');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SD', 'Sudan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SR', 'Suriname');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SJ', 'Svalbard & Jan Mayen');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SE', 'Sweden');
INSERT INTO `country` (`short_name`, `name`) VALUES ('CH', 'Switzerland');
INSERT INTO `country` (`short_name`, `name`) VALUES ('SY', 'Syria');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TW', 'Taiwan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TJ', 'Tajikistan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TZ', 'Tanzania');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TH', 'Thailand');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TL', 'Timor-Leste');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TG', 'Togo');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TK', 'Tokelau');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TO', 'Tonga');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TT', 'Trinshort_namead & Tobago');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TN', 'Tunisia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TR', 'Turkey');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TM', 'Turkmenistan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TC', 'Turks & Caicos Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('TV', 'Tuvalu');
INSERT INTO `country` (`short_name`, `name`) VALUES ('UM', 'U.S. Outlying Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO `country` (`short_name`, `name`) VALUES ('UG', 'Uganda');
INSERT INTO `country` (`short_name`, `name`) VALUES ('UA', 'Ukraine');
INSERT INTO `country` (`short_name`, `name`) VALUES ('AE', 'United Arab Emirates');
INSERT INTO `country` (`short_name`, `name`) VALUES ('GB', 'United Kingdom');
INSERT INTO `country` (`short_name`, `name`) VALUES ('US', 'United States');
INSERT INTO `country` (`short_name`, `name`) VALUES ('UY', 'Uruguay');
INSERT INTO `country` (`short_name`, `name`) VALUES ('UZ', 'Uzbekistan');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VU', 'Vanuatu');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VA', 'Vatican City');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VE', 'Venezuela');
INSERT INTO `country` (`short_name`, `name`) VALUES ('VN', 'Vietnam');
INSERT INTO `country` (`short_name`, `name`) VALUES ('WF', 'Wallis & Futuna');
INSERT INTO `country` (`short_name`, `name`) VALUES ('EH', 'Western Sahara');
INSERT INTO `country` (`short_name`, `name`) VALUES ('YE', 'Yemen');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ZM', 'Zambia');
INSERT INTO `country` (`short_name`, `name`) VALUES ('ZW', 'Zimbabwe');
